In [4]:
import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras import metrics
from read_tfrecord import *
from mtcnn_model import Pnet,cls_ohem,bbox_ohem
from tqdm import tqdm
import os
import numpy as np

In [5]:
data_path = "data/12/train_PNet_landmark.tfrecord_shuffle"

In [6]:
def load_pokemon(mode='train'):
    """ 加载pokemon数据集的工具！
    :param root:    数据集存储的目录
    :param mode:    mode:当前加载的数据是train,val,还是test
    :return:
    """
    # # 创建数字编码表,范围0-4;
    # name2label = {}  # "sq...":0   类别名:类标签;  字典 可以看一下目录,一共有5个文件夹,5个类别：0-4范围;
    # for name in sorted(os.listdir(os.path.join(root))):     # 列出所有目录;
    #     if not os.path.isdir(os.path.join(root, name)):
    #         continue
    #     # 给每个类别编码一个数字
    #     name2label[name] = len(name2label.keys())
 
    # 读取Label信息;保存索引文件images.csv
    # [file1,file2,], 对应的标签[3,1] 2个一一对应的list对象。
    # 根据目录,把每个照片的路径提取出来,以及每个照片路径所对应的类别都存储起来，存储到CSV文件中。
    size = 12
    images,labels,boxes = red_tf(data_path,size)
 
    # 图片切割成，训练70%，验证15%，测试15%。
    if mode == 'train':                                                     # 70% 训练集
        images = images[:int(0.7 * len(images))]
        labels = labels[:int(0.7 * len(labels))]
        boxes  = boxes[:int(0.7 * len(boxes))]
    elif mode == 'val':                                                     # 15% = 70%->85%  验证集
        images = images[int(0.7 * len(images)):int(0.85 * len(images))]
        labels = labels[int(0.7 * len(labels)):int(0.85 * len(labels))]
        boxes = boxes[int(0.7 * len(boxes)):int(0.85 * len(boxes))]
    else:                                                                   # 15% = 70%->85%  测试集
        images = images[int(0.85 * len(images)):]
        labels = labels[int(0.85 * len(labels)):]
        boxes = boxes[int(0.85 * len(boxes)):]
    ima = tf.data.Dataset.from_tensor_slices(images)
    lab = tf.data.Dataset.from_tensor_slices(labels)
    roi = tf.data.Dataset.from_tensor_slices(boxes)
    # ima,lab,roi = preprocess(ima,lab,roi)
    train_data = tf.data.Dataset.zip((ima, lab, roi)).shuffle(1000).batch(32)
    train_data = list(train_data.as_numpy_iterator())
    return train_data

In [10]:
for i,(img,lab,boxes) in enumerate(load_pokemon("train")):
    print(i)
    print(img)
    print(boxes)
    break

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
0
[[[[ 9.00470257e-01  7.88879871e-01  7.78909564e-01]
   [ 1.74341947e-02  1.65860786e-03  0.00000000e+00]
   [ 4.45009530e-01  4.01061982e-01  3.81063819e-01]
   ...
   [ 7.14567900e-01  5.37726879e-01  4.43208456e-01]
   [ 5.84436297e-01  4.58168507e-01  4.82645035e-01]
   [-1.12697437e-01 -1.12697437e-01 -1.12697437e-01]]

  [[ 7.14567900e-01  5.81127524e-01  5.46915293e-01]
   [ 3.60244215e-02  1.31991673e-02  0.00000000e+00]
   [ 6.58797264e-01  6.03625715e-01  5.83328485e-01]
   ...
   [ 2.40516990e-01  8.37754756e-02  0.00000000e+00]
   [ 2.12631613e-01  8.63638222e-02  9.93174016e-02]
   [ 2.86992580e-01  2.06816673e-01  2.55535245e-01]]

  [[ 2.67293081e-02  1.01918224e-02  0.00000000e+00]
   [ 8.44699502e-01  7.45529115e-01  6.88569903e-01]
   [ 7.51748323e-01  6.62605941e-01  6.53233707e-01]
   ...
   [ 6.39097691e-02  2

In [13]:
def train(eopch):
    model = Pnet()
    if os.path.exists("pnet.h5"):
        model.load_weights("pnet.h5")
    else:
        model.load_weights('./Weights/pnet_wight/pnet_30.ckpt')
 
    optimizer = keras.optimizers.Adam(learning_rate=1e-3)
    off = 1000
    acc_meter = metrics.Accuracy()
    for epoch in tqdm(range(eopch)):
 
        for i,(img,lab,boxes) in enumerate(load_pokemon("train")):
 
 
            #img = image_color_distort(img)
            # 开一个gradient tape, 计算梯度
            with tf.GradientTape() as tape:
                cls_prob, bbox_pred = model(img)
                cls_prob = tf.squeeze(cls_prob,[1,2])
                bbox_pred = tf.squeeze(bbox_pred,[1,2])
 
                cls_loss = cls_ohem(cls_prob, lab)
                bbox_loss = bbox_ohem(bbox_pred, boxes,lab)
                # landmark_loss = landmark_loss_fn(landmark_pred, landmark_batch, label_batch)
                # accuracy = cal_accuracy(cls_prob, label_batch)
 
 
                total_loss_value = cls_loss + 0.5 * bbox_loss
                grads = tape.gradient(total_loss_value, model.trainable_variables)
                optimizer.apply_gradients(zip(grads, model.trainable_variables))
            if i % 200 == 0:
                print('Training loss (for one batch) at step %s: %s' % (i, float(total_loss_value)))
                print('Seen so far: %s samples' % ((i + 1) * 6))
 
 
        for i, (v_img, v_lab1, boxes) in enumerate(load_pokemon("val")):
            v_img = image_color_distort(v_img)
            with tf.GradientTape() as tape:
                cls_prob, bbox_pred = model(v_img)
                cls_prob = tf.squeeze(cls_prob,[1,2])
                bbox_pred = tf.squeeze(bbox_pred,[1,2])
 
                cls_loss = cls_ohem(cls_prob, v_lab1)
                bbox_loss = bbox_ohem(bbox_pred, boxes,v_lab1)
                # landmark_loss = landmark_loss_fn(landmark_pred, landmark_batch, label_batch)
                # accuracy = cal_accuracy(cls_prob, label_batch)
 
 
                total_loss_value = cls_loss + 0.5 * bbox_loss
                grads = tape.gradient(total_loss_value, model.trainable_variables)
                optimizer.apply_gradients(zip(grads, model.trainable_variables))
            if i % 200 == 0:
                print('val___ loss (for one batch) at step %s: %s' % (i, float(total_loss_value)))
                print('Seen so far: %s samples' % ((i + 1) * 6))
    model.save_weights('./Weights/pnet_wight/pnet_30.ckpt')

In [14]:
train(30)

  0%|          | 0/30 [00:00<?, ?it/s]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.8359413146972656
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.4155491590499878
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.27837345004081726
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.44817817211151123
Seen so far: 6 samples


  3%|▎         | 1/30 [00:54<26:26, 54.72s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.4671699106693268
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.40162765979766846
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.3424588441848755
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.4209800660610199
Seen so far: 6 samples


  7%|▋         | 2/30 [01:53<26:44, 57.32s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.23878124356269836
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.20901580154895782
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.3559603691101074
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.32617372274398804
Seen so far: 6 samples


 10%|█         | 3/30 [02:54<26:28, 58.83s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.21128727495670319
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.26134833693504333
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.2097095102071762
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.5597795248031616
Seen so far: 6 samples


 13%|█▎        | 4/30 [03:53<25:30, 58.87s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.32778674364089966
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.3099137544631958
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.8357489109039307
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.6226744651794434
Seen so far: 6 samples


 17%|█▋        | 5/30 [04:49<24:10, 58.03s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.15539149940013885
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.3994723856449127
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.2079479992389679
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.28386083245277405
Seen so far: 6 samples


 20%|██        | 6/30 [05:45<22:54, 57.26s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.13109105825424194
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.07819440960884094
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.25583767890930176
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.2956675887107849
Seen so far: 6 samples


 23%|██▎       | 7/30 [06:38<21:21, 55.72s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.39475417137145996
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.20401710271835327
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.10113663971424103
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.5593470335006714
Seen so far: 6 samples


 27%|██▋       | 8/30 [07:35<20:33, 56.06s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.26225367188453674
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.16128742694854736
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.6717553734779358
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.22885854542255402
Seen so far: 6 samples


 30%|███       | 9/30 [08:32<19:47, 56.53s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.4598860442638397
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.16377052664756775
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.1625930368900299
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.36728572845458984
Seen so far: 6 samples


 33%|███▎      | 10/30 [09:30<18:56, 56.82s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.3414551019668579
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.3016895353794098
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.30138951539993286
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.19241511821746826
Seen so far: 6 samples


 37%|███▋      | 11/30 [10:26<17:59, 56.80s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.26393577456474304
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.43968844413757324
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.5612716674804688
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.2735404372215271
Seen so far: 6 samples


 40%|████      | 12/30 [11:21<16:52, 56.23s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.14471586048603058
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.22394926846027374
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.48972246050834656
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.25902625918388367
Seen so far: 6 samples


 43%|████▎     | 13/30 [12:14<15:39, 55.25s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.1740548312664032
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.14161084592342377
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.21832971274852753
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.31117185950279236
Seen so far: 6 samples


 47%|████▋     | 14/30 [13:08<14:35, 54.70s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.370607852935791
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.0887947827577591
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.27876147627830505
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.2512228488922119
Seen so far: 6 samples


 50%|█████     | 15/30 [14:02<13:39, 54.62s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.189750537276268
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.17744845151901245
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.2021373063325882
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.08501515537500381
Seen so far: 6 samples


 53%|█████▎    | 16/30 [14:56<12:43, 54.51s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.31078431010246277
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.13701222836971283
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.16774658858776093
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.24951130151748657
Seen so far: 6 samples


 57%|█████▋    | 17/30 [15:52<11:50, 54.69s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.231546550989151
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.18861792981624603
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.2362194061279297
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.20827516913414001
Seen so far: 6 samples


 60%|██████    | 18/30 [16:52<11:18, 56.54s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.07180434465408325
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.16531826555728912
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.19397851824760437
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.11226218938827515
Seen so far: 6 samples


 63%|██████▎   | 19/30 [17:49<10:21, 56.54s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.16892172396183014
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.14401447772979736
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.19230926036834717
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.18077287077903748
Seen so far: 6 samples


 67%|██████▋   | 20/30 [18:45<09:24, 56.50s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.11585810780525208
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.11359743028879166
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.11347741633653641
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.12124735116958618
Seen so far: 6 samples


 70%|███████   | 21/30 [19:45<08:36, 57.41s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.11416196078062057
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.1410733163356781
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.11333727091550827
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.15540054440498352
Seen so far: 6 samples


 73%|███████▎  | 22/30 [20:47<07:49, 58.72s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.13033220171928406
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.0984228178858757
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.22125379741191864
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.4421785771846771
Seen so far: 6 samples


 77%|███████▋  | 23/30 [21:44<06:49, 58.47s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.07140830159187317
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.13714268803596497
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.05262817069888115
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.30336976051330566
Seen so far: 6 samples


 80%|████████  | 24/30 [22:40<05:44, 57.48s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.12243003398180008
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.18024620413780212
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.2584759294986725
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.22001716494560242
Seen so far: 6 samples


 83%|████████▎ | 25/30 [23:34<04:42, 56.48s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.13958898186683655
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.2355027198791504
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.07934591174125671
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.33986231684684753
Seen so far: 6 samples


 87%|████████▋ | 26/30 [24:29<03:43, 55.96s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.06421727687120438
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.07117953896522522
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.11645005643367767
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.21379454433918
Seen so far: 6 samples


 90%|█████████ | 27/30 [25:22<02:45, 55.21s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.06792408227920532
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.1246570572257042
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.1261330097913742
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.4066201448440552
Seen so far: 6 samples


 93%|█████████▎| 28/30 [26:16<01:49, 54.93s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.03416148200631142
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.03891266882419586
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.1922222077846527
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.2704184949398041
Seen so far: 6 samples


 97%|█████████▋| 29/30 [27:10<00:54, 54.51s/it]

<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
Training loss (for one batch) at step 0: 0.04365459084510803
Seen so far: 6 samples
Training loss (for one batch) at step 200: 0.18410339951515198
Seen so far: 1206 samples
Training loss (for one batch) at step 400: 0.06513691693544388
Seen so far: 2406 samples
<MapDataset shapes: {image/encoded: (), image/label: (), image/roi: (4,)}, types: {image/encoded: tf.string, image/label: tf.int64, image/roi: tf.float32}>
val___ loss (for one batch) at step 0: 0.11707638204097748
Seen so far: 6 samples


100%|██████████| 30/30 [28:04<00:00, 56.14s/it]
